### ISSUE TITLE
Error: You cannot upload file for not persisted record. Save record first

### ISSUE THREAD

**Issue by Amixengineer** [SoftwareBrothers/admin-bro-upload#14]
Hello dear @wojtek-krysiak, 

it seems that upload feature for mongoose does not work as it is expected. i get these two errors.

on the response tab in network
```
Error: new action can be invoked only via `post` http method
    at Object.handler (/Users/amix/Desktop/BndNail-NodeJs-Project/node_modules/admin-bro/lib/backend/actions/new/new-action.js:76:11)
    at ActionDecorator.invokeHandler (/Users/amix/Desktop/BndNail-NodeJs-Project/node_modules/admin-bro/lib/backend/decorators/action/action-decorator.js:117:26)
    at ActionDecorator.handler (/Users/amix/Desktop/BndNail-NodeJs-Project/node_modules/admin-bro/lib/backend/decorators/action/action-decorator.js:73:30)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async handler (/Users/amix/Desktop/BndNail-NodeJs-Project/node_modules/admin-bro-expressjs/plugin.js:59:22)
```

on terminal
```
Error: You cannot upload file for not persisted record. Save record first
    at Object.exports.buildRemotePath (/Users/amix/Desktop/BndNail-NodeJs-Projec\node_modules\@admin-bro\upload\build\features\upload-file\utils\build-remote-path.js:22:15)
    at Promise.all.uploadedFiles.map (/Users/amix/Desktop/BndNail-NodeJs-Projec\node_modules\@admin-bro\upload\build\features\upload-file\factories\update-record-factory.js:36:53)
    at Array.map (<anonymous>)
    at updateRecord (/Users/amix/Desktop/BndNail-NodeJs-Projec\node_modules\@admin-bro\upload\build\features\upload-file\factories\update-record-factory.js:35:62)
    at prevPromise.then.modifiedResponse (/Users/amix/Desktop/BndNail-NodeJs-Projec\node_modules\admin-bro\lib\backend\decorators\action\action-decorator.js:147:99)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
after searching through issues I came across to one comment that had the same problem as mine

https://github.com/SoftwareBrothers/admin-bro/issues/95#issuecomment-708630040

**Comment by Amixengineer** [comment]
It works well with admin-bro@3.3.0-beta.21 but admin-bro@3.3.1 does return the error

**Comment by Amixengineer** [comment]
fixed
problem was related to deprecated admin-bro-mongoose and admin-bro-expressjs.

**Comment by Saurabhkmr98** [comment]
@Amixengineer I am facing similar issue while uploading file to s3..
These are the code snippets for options, package.json and schema.

`const teacherParams = {
  resource: Teacher,
  options: {
    listProperties: ["name", "email", "phone", "status"],
  },
  features: [
    uploadFeature({
      provider: {
        aws: {
          region: env.region,
          bucket: env.bucket,
          secretAccessKey: env.secretAccessKey,
          accessKeyId: env.accessKeyId,
          expires: 0,
        },
      },
      properties: {
        key: "fileUrl",
        mimeType: "mimeType",
      },
      validation: {
        mimeTypes: ["image/png", "image/jpg", "image/jpeg"],
      },
      multiple: true,
    }),
  ],
};`

`"dependencies": {
    "@admin-bro/upload": "^1.3.1",
    "admin-bro": "^4.0.1",
    "admin-bro-expressjs": "^2.1.1",
    "admin-bro-mongoose": "^0.5.2",`
    
    `const teacherSchema = new Schema({
  name: String,
  email: String,
  about: String,
  countryCode: Object,
  phone: String,
  createdAt: Date,
  password: String,
  status: Number,
  permissionLevel: Number,
  updatedAt: Date,
  // updatedBy: Schema.Types.ObjectId,
  timeZone: String,
  fileUrl: [
    {
      type: String,
    },
  ],
  mimeType: [
    {
      type: String,
    },
  ],
  imageURL: String,
});`

Any idea how to fix this @wojtek-krysiak @Amixengineer

**Comment by radonejr** [comment]
Hello guys,

for anyone still facing this issue i managed to fix it in my case by making some changes in admin-bro-mongoose/src/resource.js  file:

line 9 :
-    return mongooseDocument.toObject()
+    return {...mongooseDocument.toObject(),_id:mongooseDocument._id.toString()}

line 18 :
-    return mongooseDocument.toObject()
+    return {...mongooseDocument.toObject(),_id:mongooseDocument._id.toString()}

**Comment by MUHAMMAD-DHARIWAL** [comment]
for anyone still facing this issue i managed to fix it in my case by making some changes in database models defination defined the primary attribute as 'id' admin js upload default configuration look for this attribute in the record if it not named as 'id' this issue comes hope admin js will fix this bug soon
